host: kafka
port: 9092
vendors:
  - vendor:
    name: jenkins
    host: http://onmunoz-box.zpn.intel.com
    port: 9090
    username: admin
    password: admin
  - vendor:
    name: travis
    host: www.command2
    port: 9090
    username: admin
    password: 123
