host: kafka
port: 9092
vendors:
  - vendor:
    name: jenkins
    host: http://k8s-ci.intel.com
    port: 9090
    username: admin
    password: Frig0Bar
  - vendor:
    name: travis
    host: www.command2
    port: 9090
    username: admin
    password: 123
