host: localhost
port: 9092
vendors:
  - vendor:
    name: jenkins
    host: www.command
    port: 8080
    username: admin
    password: admin
  - vendor:
    name: travis
    host: www.command2
    port: 9090
    username: admin
    password: 123
