apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: NodePort
  ports:
    - port: 9092
      name: inside
      targetPort: 9092
      nodePort: 30092
  selector:
    name: kafka
---
apiVersion: v1
kind: Pod
metadata:
  name: ci-cd-pod
spec:
  containers:
  - image: wurstmeister/zookeeper
    name: zookeeper
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2181
  - image: wurstmeister/kafka
    name: kafka
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 9092
    env:
      - name: KAFKA_ADVERTISED_LISTENERS
        value: INSIDE://:9092
      - name: KAFKA_CREATE_TOPICS
        value: jenkins-requests:1:1,jenkins-responses:1:1
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: INSIDE
      - name: KAFKA_LISTENERS
        value: INSIDE://:9092
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: INSIDE:PLAINTEXT 
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: :2181
  - image: ci-cd-broker:devel
    resources: {}
    args: ["bash", "-c"," echo '0.0.0.0 kafka' >> /etc/hosts; while true; do echo Trying to start Broker...;go run main.go; sleep 5;done"]
    name: broker
    imagePullPolicy: IfNotPresent
             

  
