version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "jenkins.requests:1:1,jenkins.responses:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  broker:
    build:
      context: .
    command: >
      bash -c "
        while true;
        do
          echo Trying to start Broker...;
          go run main.go;
          sleep 5;
        done;"
    depends_on:
      - zookeeper
      - kafka
