version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka:9092"
      KAFKA_LISTENERS: "INSIDE://:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"
      KAFKA_CREATE_TOPICS: "jenkins-requests:1:1,jenkins-responses:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    ports:
      - "8080:8080"

  broker:
    build:
      context: .
    command: >
      bash -c "
        while true;
        do
          echo Trying to start Broker...;
          go run main.go;
          sleep 5;
        done;"
    depends_on:
      - zookeeper
      - kafka
      - jenkins
